[project]
authors = ["donkey"]
entry = "main.sw"
license = "Apache-2.0"
name = "Strategy"

[dependencies]
interfaces = { path = "../../libraries/interfaces" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }